create table t_content (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title text null,
    content text null,
    media_url text null,
    media_type character varying(50) null,
    media_created_at timestamp with time zone null,
    reference_url text null,
    reference_type character varying(50) null,
    reference_created_at timestamp with time zone null,
    creator VARCHAR(255) NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    source_url VARCHAR(255),
    version INTEGER DEFAULT 0,
    lang VARCHAR(2) DEFAULT 'en',
    tags TEXT,
    created_at timestamp with time zone null default (now() at time zone 'utc'::text),
    updated_at timestamp with time zone null default (now() at time zone 'utc'::text),
    scheduled_for timestamp with time zone null default (now() at time zone 'utc'::text)
);
