CREATE TABLE t_github_projects (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    rank INTEGER,
    username VARCHAR(255),
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    description TEXT,
    program_language VARCHAR(255),
    total_stars INTEGER,
    forks INTEGER,
    new_stars INTEGER,
    contributors TEXT,
    periodicity VARCHAR(50) NOT NULL,
    creator VARCHAR(255) NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    source_url VARCHAR(255),
    version INTEGER DEFAULT 0,
    lang VARCHAR(2) DEFAULT 'en',
    tags TEXT,
    created_at timestamp with time zone null default (now() at time zone 'utc'::text),
    updated_at timestamp with time zone null default (now() at time zone 'utc'::text)
);