CREATE TABLE t_media (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    media_url VARCHAR(255),
    media_b64_content TEXT,
    media_type VARCHAR(50) NOT NULL,
    title VARCHAR(255),
    description TEXT,
    likes INTEGER DEFAULT 0,
    hearts INTEGER DEFAULT 0,
    prompt TEXT,
    model VARCHAR(255),
    author VARCHAR(255),
    media_created_at timestamp with time zone null,
    creator VARCHAR(255) NOT NULL,
    source_name VARCHAR(255) NOT NULL,
    source_url VARCHAR(255),
    version INTEGER DEFAULT 0,
    lang VARCHAR(2) DEFAULT 'en',
    tags TEXT,
    created_at timestamp with time zone null default (now() at time zone 'utc'::text),
    updated_at timestamp with time zone null default (now() at time zone 'utc'::text)
);