create table t_research_papers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title text,
    abstract text null,
    authors text,
    license text null,
    paper_url character varying(255) null,
    code_url character varying(255) null,
    media_url character varying(255) null,
    paper_submitted_at timestamp with time zone null,
    source_name character varying(255),
    source_id text,
    source_url character varying(255) null,
    version integer default 0,
    tags text,
    creator character varying(255),
    lang character varying(2) default 'en',
    created_at timestamp with time zone null default (now() at time zone 'utc'::text),
    updated_at timestamp with time zone null default (now() at time zone 'utc'::text)
)